### PR TITLE
Support Ruby 2.3.1

### PR DESCRIPTION
**Pull request by ivaravko**
Adds support for last stable ruby - 2.3.1

### CODE REVIEW

**Comment by etolstoy** [comment]
Looks like Travis can't install this version of ruby.

**Comment by ivaravko** [comment]
@etolstoy Travis-ci need build binary for Mac OS - https://github.com/travis-ci/travis-rubies/issues/21 .

**Comment by ivaravko** [comment]
@etolstoy BTW image xcode7.3 includes Ruby 2.3.1 . All tests passed.

**Comment by etolstoy** [comment]
Great, merging!

**Pull request merged**
